### ISSUE TITLE
Midi Learn (still? or again?) gets lost on reloading presets.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1293]
When reloading a .mrec preset where some midi-source plugin  modulates a target sampler/synth etc.
via some midi-learned parameters on the target, the [m] still is shown, but nothing happens until "relearn"
is clicked. 

I think we had this issue already at some time. I also think this was fixed at some point?
I can't remember, but it still is not working.

Best,
tL.

**Comment by kmatheussen** [comment]
It should be fixed, but only for new song/mrec files. I don't think the necessary information was saved, so it wasn't really possible to fix loading old songs and mrec files. Does it work if you load a relearned .mrec-file?

**Comment by Lykdraft** [comment]
Yes, I resaved the configuration again, still doesn't work on loading the .mrec preset.
Same behaviour.

**Comment by kmatheussen** [comment]
Guess I only fixed this when saving to song, not when saving .mrec files. I'm pretty sure I didn't think about .mrec files when fixing it for song files.
