### ISSUE TITLE
force as current block, not forcing as current block as it should?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1297]
Take a look...
I think when Radium plays back a song, it overrides this setting.
Not sure if this is intended though?

![lookAtThis](https://user-images.githubusercontent.com/18437561/99150384-8b5bda00-2694-11eb-8457-09e313f30fbe.gif)

**Comment by kmatheussen** [comment]
Yeah, it's intended. Don't remember why. Maybe it shouldn't be like that.

**Comment by Lykdraft** [comment]
Hm, alright. Maybe you want to take a look at that, play around with this a little bit for yourself and see what makes more sense. 
In my head "force lock" = locked, no matter what, but your mileage may vary.

**Comment by kmatheussen** [comment]
I think the only reason was that I didn't want to think about whether it was safe to unbound the assumption that the currently playing block is also the visible one.

**Comment by kmatheussen** [comment]
("unbind", not "unbound"). I mean, in the source code. It might crash in mysterious places if this is fixed. But it probably needs to be done.

**Comment by Lykdraft** [comment]
I understand. 

I think it might not be that urgent though, it is just a bit annoying.

_(Maybe just leave it open as a reminder for some time later down the road.
because I think it is safe to assume that if a user decided to "force lock" something, that this is exactly what he wants to happen.)_

**Comment by kmatheussen** [comment]
Should have been fixed in 5.9.81 I think.

**Comment by Lykdraft** [comment]
Can you double-check this?
Yesterday I thought it still doesn't work, actually wanted to write in here then,
but I needed to leave until Monday so I couldn't.

**Comment by kmatheussen** [comment]
What I implemented works here, but let me know if something doesn't work as
expected.
